WebApplication/Models/PlanowanieTreningow.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using WebApplication.Areas.Identity.Data;

namespace WebApplication.Models
{
    [Table("PlanowaneTreningi")]
    public class PlanowanieTreningow
    {
        [Key]
        public int id { get; set; }
        [Required, ForeignKey("uzytkownik")]
        public int id_uzytkownika { get; set; }
        [Required, ForeignKey("trening")]
        public int id_treningu { get; set; }
        [Required]
        public DateTime data { get; set; }

        public virtual Uzytkownik uzytkownik { get; set; }
        public virtual Trening trening { get; set; }

    }
}

WebApplication/Controllers/PlanowanieTreningowController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication.Data;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    [Authorize]
    public class PlanowanieTreningowController : Controller
    {
        private readonly MyContext _context;

        public PlanowanieTreningowController(MyContext context)
        {
            _context = context;
        }

        // GET: PlanowanieTreningow
        public async Task<IActionResult> Index()
        {
            int userId = int.Parse(User.Identity.GetUserId());
            var myContext = _context.planowaneTreningi.Include(p => p.trening).Where(x => x.id_uzytkownika == userId );
            return View(await myContext.ToListAsync());
        }

        // GET: PlanowanieTreningow/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            int userId = int.Parse(User.Identity.GetUserId());
            var planowanieTreningow = await _context.planowaneTreningi
                .Include(p => p.trening)
                .Include(p => p.uzytkownik)
                .FirstOrDefaultAsync(m => m.id == id);
            if (planowanieTreningow == null)
            {
                return NotFound();
            }

            if (planowanieTreningow.id_uzytkownika != int.Parse(User.Identity.GetUserId()))
                return RedirectToAction("Index");

            return View(planowanieTreningow);
        }

        
        // GET: PlanowanieTreningow/Create
        public IActionResult Create(string id_string)
        {
            ViewData["id_treningu"] = new SelectList(_context.treningi, "id_treningu", "nazwa");
            if (!String.IsNullOrEmpty(id_string))
            {
                int id = int.Parse(id_string);
                PlanowanieTreningow training = new PlanowanieTreningow();
                training.id_treningu = id;
                training.data = DateTime.Now;
                //training.trening = _context.treningi.Where(x => x.id_treningu == id).FirstOrDefault();
                return View(training);
            }

            return View();
        }

        // POST: PlanowanieTreningow/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id_uzytkownika,id_treningu,data")] PlanowanieTreningow planowanieTreningow)
        {
            if (ModelState.IsValid)
            {
                planowanieTreningow.id_uzytkownika = int.Parse(User.Identity.GetUserId());
                _context.Add(planowanieTreningow);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["id_treningu"] = new SelectList(_context.treningi, "id_treningu", "nazwa", planowanieTreningow.id_treningu);
            return View(planowanieTreningow);
        }

        /*/ GET: PlanowanieTreningow/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var planowanieTreningow = await _context.planowaneTreningi.FindAsync(id);
            if (planowanieTreningow == null)
            {
                return NotFound();
            }
            ViewData["id_treningu"] = new SelectList(_context.treningi, "id_treningu", "nazwa", planowanieTreningow.id_treningu);
            ViewData["id_uzytkownika"] = new SelectList(_context.uzytkownicy, "Id", "Id", planowanieTreningow.id_uzytkownika);
            return View(planowanieTreningow);
        }

        // POST: PlanowanieTreningow/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id_uzytkownika,id_treningu,data")] PlanowanieTreningow planowanieTreningow)
        {
            if (id != planowanieTreningow.id_treningu)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(planowanieTreningow);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlanowanieTreningowExists(planowanieTreningow.id_treningu))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["id_treningu"] = new SelectList(_context.treningi, "id_treningu", "nazwa", planowanieTreningow.id_treningu);
            ViewData["id_uzytkownika"] = new SelectList(_context.uzytkownicy, "Id", "Id", planowanieTreningow.id_uzytkownika);
            return View(planowanieTreningow);
        }*/

        // GET: PlanowanieTreningow/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var planowanieTreningow = await _context.planowaneTreningi
                .Include(p => p.trening)
                .Include(p => p.uzytkownik)
                .FirstOrDefaultAsync(m => m.id == id);
            if (planowanieTreningow == null)
            {
                return NotFound();
            }

            if (planowanieTreningow.id_uzytkownika != int.Parse(User.Identity.GetUserId()))
                return RedirectToAction("Index");

            return View(planowanieTreningow);
        }

        // POST: PlanowanieTreningow/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var planowanieTreningow = await _context.planowaneTreningi.FindAsync(id);

            if (planowanieTreningow.id_uzytkownika != int.Parse(User.Identity.GetUserId()))
                return RedirectToAction("Index");

            _context.planowaneTreningi.Remove(planowanieTreningow);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlanowanieTreningowExists(int id)
        {
            return _context.planowaneTreningi.Any(e => e.id_treningu == id);
        }
    }
}

WebApplication/Controllers/TreningController.cs
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Security.Cryptography.Xml;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication.Data;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    [Authorize]
    public class TreningController : Controller
    {
        private readonly MyContext _context;

        public TreningController(MyContext context)
        {
            _context = context;
        }

        // GET: Trening
        public async Task<IActionResult> Index(String searchString, String category)
        {
            ViewData["currentSearchString"] = searchString;

            ViewBag.userId = int.Parse(User.Identity.GetUserId());

            Rola usersRole = _context.role.Include(k => k.uzytkownicy)
                                          .FirstOrDefault(m => m.nazwa == "trener");

            List<int> trainersIds = new List<int>();
            if(usersRole != null)
                foreach (var user in usersRole.uzytkownicy)
                {
                    trainersIds.Add(user.id_uzytkownika);
                }

            ViewBag.trainersIds = trainersIds;

            SelectList categories = new SelectList(_context.kategoriaTreningu, "id_kategorii", "nazwa");
            List<SelectListItem> _categories = categories.ToList();
            _categories.Insert(0, new SelectListItem() { Value = "-1", Text = "Wszystkie" });
            ViewBag.category = new SelectList((IEnumerable<SelectListItem>)_categories, "Value", "Text");

            var trainings = _context.treningi.Where(k => true);

            if (!String.IsNullOrEmpty(searchString))
            {
                trainings = trainings.Where(k => k.nazwa.Contains(searchString));
            }
            
            if(!String.IsNullOrEmpty(category))
            {
                int category_id = int.Parse(category);
                if(category_id != -1)
                    trainings = trainings.Where(k => k.id_kategorii == category_id);
            }
                
            return View(await trainings.Include(t => t.kategoria).Include(t => t.uzytkownik).ToListAsync());

        }

        // GET: Trening/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trening = await _context.treningi
                .Include(t => t.kategoria)
                .Include(t => t.uzytkownik)
                .FirstOrDefaultAsync(m => m.id_treningu == id);

            ViewBag.trainingDetails = _context.treningSzczegoly.Where(k => k.id_treningu == id)
                                        .Include(k => k.cwiczenie)
                                        .ToList();

            ViewBag.userId = int.Parse(this.User.Identity.GetUserId());
            ViewBag.treningOwner = trening.id_uzytkownika;

            if (trening == null)
            {
                return NotFound();
            }

            return View(trening);
        }

        // GET: Trening/Create
        public IActionResult Create()
        {
            ViewData["id_kategorii"] = new SelectList(_context.kategoriaTreningu, "id_kategorii", "nazwa");
            return View();
        }

        // POST: Trening/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id_treningu,nazwa,id_kategorii")] Trening trening)
        {
            trening.id_uzytkownika = int.Parse(User.Identity.GetUserId());
            if (ModelState.IsValid)
            {
                _context.Add(trening);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["id_kategorii"] = new SelectList(_context.kategoriaTreningu, "id_kategorii", "nazwa", trening.id_kategorii);
            return View(trening);
        }

        // GET: Trening/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trening = await _context.treningi.FindAsync(id);
            if (trening == null)
            {
                return NotFound();
            }
            if (trening.id_uzytkownika != int.Parse(User.Identity.GetUserId()))
                return RedirectToAction("Details", new { id = trening.id_treningu });

            ViewData["id_kategorii"] = new SelectList(_context.kategoriaTreningu, "id_kategorii", "nazwa", trening.id_kategorii);
            return View(trening);
        }

        // POST: Trening/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id_treningu,nazwa,id_kategorii")] Trening trening)
        {
            if (id != trening.id_treningu)
            {
                return NotFound();
            }

            if (trening.id_uzytkownika != int.Parse(User.Identity.GetUserId()))
                return RedirectToAction("Details", new { id = trening.id_treningu });

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(trening);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TreningExists(trening.id_treningu))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["id_kategorii"] = new SelectList(_context.kategoriaTreningu, "id_kategorii", "nazwa", trening.id_kategorii);
            return View(trening);
        }

        // GET: Trening/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trening = await _context.treningi
                .Include(t => t.kategoria)
                .Include(t => t.uzytkownik)
                .FirstOrDefaultAsync(m => m.id_treningu == id);
            if (trening == null)
            {
                return NotFound();
            }

            if (trening.id_uzytkownika != int.Parse(User.Identity.GetUserId()))
                return RedirectToAction("Details", new { id = trening.id_treningu });

            return View(trening);
        }

        // POST: Trening/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var trening = await _context.treningi.FindAsync(id);

            if (trening.id_uzytkownika != int.Parse(User.Identity.GetUserId()))
                return RedirectToAction("Details", new { id = trening.id_treningu });

            _context.treningi.Remove(trening);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // POST: Trening/DeleteExercise/5/6
        [HttpPost, ActionName("DeleteExercise")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteExercise(int idt,int idc)
        {
            var cwiczenie = _context.treningSzczegoly.Include(k => k.trening)
                .FirstOrDefault(k => k.id_treningu == idt && k.id_cwiczenia == idc);
            if (cwiczenie == null)
                return RedirectToAction("Index");

            if (cwiczenie.trening.id_uzytkownika != int.Parse(User.Identity.GetUserId()))
                return RedirectToAction("Details", new { id = cwiczenie.id_treningu });

            _context.treningSzczegoly.Remove(cwiczenie);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Details), new { id = idt});
        }

        // GET: Trening/AddExercise/5       
        public async Task<IActionResult> AddExercise(int? id, string category)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trening = await _context.treningi.FindAsync(id);
            if (trening == null)
            {
                return NotFound();
            }
            if (trening.id_uzytkownika != int.Parse(User.Identity.GetUserId()))
                return RedirectToAction("Details", new { id = trening.id_treningu });

            TreningSzczegoly tszczegoly = new TreningSzczegoly();
            tszczegoly.id_treningu = trening.id_treningu;
            ViewBag.trainingId = id;
            
            SelectList categories = new SelectList(_context.kategoriaCwiczenia, "id_kategorii", "nazwa");
            List<SelectListItem> _categories = categories.ToList();
            _categories.Insert(0, new SelectListItem() { Value = "-1", Text = "Wszystkie" });
            ViewBag.category = new SelectList((IEnumerable<SelectListItem>)_categories, "Value", "Text");

            if (!String.IsNullOrEmpty(category) && category != "-1")
            {
                int idc = int.Parse(category);
                ViewData["id_cwiczenia"] = new SelectList(_context.cwiczenia.Where(k => k.id_kategorii == idc), "id_cwiczenia", "nazwa");
            }

WebApplication/Views/PlanowanieTreningow/Create.cshtml
@model WebApplication.Models.PlanowanieTreningow

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>PlanowanieTreningow</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="id_treningu" class="control-label"></label>
                <select asp-for="id_treningu" class ="form-control" asp-items="ViewBag.id_treningu"></select>
            </div>
            <div class="form-group">
                <label asp-for="data" class="control-label"></label>
                <input asp-for="data" class="form-control" />
                <span asp-validation-for="data" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Powrot do listy</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication/Views/PlanowanieTreningow/Delete.cshtml
@model WebApplication.Models.PlanowanieTreningow

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Usuń</h1>

<h3>Jesteś pewien, że chcesz usunąć trening z listy planowanych?</h3>
<div>
    <h4>PlanowanieTreningow</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.uzytkownik)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.uzytkownik.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.trening)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.trening.nazwa)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id_uzytkownika" />
        <input type="hidden" asp-for="id_treningu" />
        <input type="hidden" asp-for="data" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Powrot do listy</a>
    </form>
</div>

WebApplication/Views/PlanowanieTreningow/Details.cshtml
@model WebApplication.Models.PlanowanieTreningow

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>PlanowanieTreningow</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.uzytkownik)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.uzytkownik.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.trening)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.trening.nazwa)
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="Trening" asp-action="Details" asp-route-id="@Model.id">Zobacz szczegóły treningu</a>
    <a asp-action="Index">Powrót do listy zadan</a>
</div>

WebApplication/Views/PlanowanieTreningow/Edit.cshtml
@model WebApplication.Models.PlanowanieTreningow

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>PlanowanieTreningow</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id_treningu" />
            <input type="hidden" asp-for="data" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Powrót do listy </a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication/Views/PlanowanieTreningow/Index.cshtml
@model IEnumerable<WebApplication.Models.PlanowanieTreningow>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Zaplanowane treningi</h1>

<p>
    <a asp-action="Create">Zaplanuj trening</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.trening)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.data)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.trening.nazwa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.data)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id=item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.id })
            </td>
        </tr>
}
    </tbody>
</table>