WebApplication/Models/Cwiczenie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication.Models
{
    [Table("Cwiczenia")]
    public class Cwiczenie
    {
        [Key]
        public int id_cwiczenia { get; set; }
        [Required]
        [Column(TypeName = "varchar(20)")]
        public string nazwa { get; set; }
        [Column(TypeName = "varchar(1000)")]
        [Required]
        public string opis { get; set; }
        public int spalone_kalorie { get; set; }
        [Required]
        [ForeignKey("kategoria")]
        public int id_kategorii { get; set; }


        public virtual KategoriaCwiczenia kategoria { get; set; }
        public virtual ICollection<TreningSzczegoly> treningi { get; set; }

        public override string ToString()
        {
            return nazwa;
        }

    }
}

WebApplication/Controllers/CwiczenieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication.Data;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    [Authorize]
    public class CwiczenieController : Controller
    {
        private readonly MyContext _context;

        public CwiczenieController(MyContext context)
        {
            _context = context;
        }

        // GET: Cwiczenie
        //sort == 0 and other data arent sorted
        //sort == 1 data are sorted ascending
        //sort == 2 data are sorted descending
        public async Task<IActionResult> Index(String searchString, String category, int sort)
        {
            ViewData["currentSearchString"] = searchString;
            ViewData["currentSort"] = (sort + 1)%3;

            ViewBag.isTrainer = isTrainer();
            var exercises = _context.cwiczenia.Where(k => true);

            SelectList categories = new SelectList(_context.kategoriaCwiczenia, "id_kategorii", "nazwa");
            List<SelectListItem> _categories = categories.ToList();
            _categories.Insert(0, new SelectListItem() { Value = "-1", Text = "Wszystkie" });
            ViewBag.category = new SelectList((IEnumerable<SelectListItem>)_categories, "Value", "Text");

            if (!String.IsNullOrEmpty(category))
            {
                int id = int.Parse(category);
                if(id!= -1)
                    exercises = exercises.Where(k => k.id_kategorii == id);
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                exercises = exercises.Include(c => c.kategoria).Where(k => k.nazwa.Contains(searchString));
                switch(sort)
                {
                    case 2:
                        exercises = exercises.OrderBy(k => k.spalone_kalorie);
                        break;

                    case 1:
                        exercises = exercises.OrderByDescending(k => k.spalone_kalorie);
                        break;
                    default:

                        break;
                }
                
                return View(await exercises.ToListAsync());
            }
            else
            {
                exercises = exercises.Include(c => c.kategoria).AsQueryable();
                switch (sort)
                {
                    case 2:
                        exercises = exercises.OrderBy(k => k.spalone_kalorie);
                        break;

                    case 1:
                        exercises = exercises.OrderByDescending(k => k.spalone_kalorie);
                        break;
                    default:

                        break;
                }

                return View(await exercises.ToListAsync());
            }
        }

        // GET: Cwiczenie/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cwiczenie = await _context.cwiczenia
                .Include(c => c.kategoria)
                .FirstOrDefaultAsync(m => m.id_cwiczenia == id);
            if (cwiczenie == null)
            {
                return NotFound();
            }

            return View(cwiczenie);
        }

        // GET: Cwiczenie/Create
        public IActionResult Create()
        {
            if (!this.isTrainer())
                return RedirectToAction("Index");

            ViewData["id_kategorii"] = new SelectList(_context.kategoriaCwiczenia, "id_kategorii", "nazwa");
            return View();
        }

        // POST: Cwiczenie/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id_cwiczenia,nazwa,opis,spalone_kalorie,id_kategorii")] Cwiczenie cwiczenie)
        {
            if (!this.isTrainer())
                return RedirectToAction("Index");

            if (ModelState.IsValid)
            {
                _context.Add(cwiczenie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["id_kategorii"] = new SelectList(_context.kategoriaCwiczenia, "id_kategorii", "nazwa", cwiczenie.id_kategorii);
            return View(cwiczenie);
        }

        // GET: Cwiczenie/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (!this.isTrainer())
                return RedirectToAction("Index");

            if (id == null)
            {
                return NotFound();
            }

            var cwiczenie = await _context.cwiczenia.FindAsync(id);
            if (cwiczenie == null)
            {
                return NotFound();
            }
            ViewData["id_kategorii"] = new SelectList(_context.kategoriaCwiczenia, "id_kategorii", "nazwa", cwiczenie.id_kategorii);
            return View(cwiczenie);
        }

        // POST: Cwiczenie/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id_cwiczenia,nazwa,opis,spalone_kalorie,id_kategorii")] Cwiczenie cwiczenie)
        {
            if (!this.isTrainer())
                return RedirectToAction("Index");

            if (id != cwiczenie.id_cwiczenia)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cwiczenie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CwiczenieExists(cwiczenie.id_cwiczenia))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["id_kategorii"] = new SelectList(_context.kategoriaCwiczenia, "id_kategorii", "nazwa", cwiczenie.id_kategorii);
            return View(cwiczenie);
        }

        // GET: Cwiczenie/Delete/5

        public async Task<IActionResult> Delete(int? id)
        {
            if (!this.isTrainer())
                return RedirectToAction("Index");

            if (id == null)
            {
                return NotFound();
            }

            var cwiczenie = await _context.cwiczenia
                .Include(c => c.kategoria)
                .FirstOrDefaultAsync(m => m.id_cwiczenia == id);
            if (cwiczenie == null)
            {
                return NotFound();
            }

            return View(cwiczenie);
        }

        // POST: Cwiczenie/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (!this.isTrainer())
                return RedirectToAction("Index");

            var cwiczenie = await _context.cwiczenia.FindAsync(id);
            _context.cwiczenia.Remove(cwiczenie);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CwiczenieExists(int id)
        {
            return _context.cwiczenia.Any(e => e.id_cwiczenia == id);
        }

        private bool isTrainer()
        {
            int userId = int.Parse(User.Identity.GetUserId());
            List<RolaUzytkownika> usersRoles = _context.RolaUzytkownika.Where(k => k.id_uzytkownika == userId).Include(c => c.rola).ToList();

            foreach (var usersRole in usersRoles)
                if (usersRole.rola.nazwa == "trener" || usersRole.rola.nazwa == "admin")
                    return true;
            return false;
        }
    }
}

WebApplication/Views/Cwiczenie/Create.cshtml
@model WebApplication.Models.Cwiczenie

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Cwiczenie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nazwa" class="control-label"></label>
                <input asp-for="nazwa" class="form-control" />
                <span asp-validation-for="nazwa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="opis" class="control-label"></label>
                <input asp-for="opis" class="form-control" />
                <span asp-validation-for="opis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="spalone_kalorie" class="control-label"></label>
                <input asp-for="spalone_kalorie" class="form-control" />
                <span asp-validation-for="spalone_kalorie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="id_kategorii" class="control-label"></label>
                <select asp-for="id_kategorii" class ="form-control" asp-items="ViewBag.id_kategorii"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication/Views/Cwiczenie/Delete.cshtml
@model WebApplication.Models.Cwiczenie

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cwiczenie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nazwa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nazwa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.opis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.opis)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.spalone_kalorie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.spalone_kalorie)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.kategoria)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.kategoria.nazwa)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id_cwiczenia" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApplication/Views/Cwiczenie/Details.cshtml
@model WebApplication.Models.Cwiczenie

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Cwiczenie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nazwa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nazwa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.opis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.opis)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.spalone_kalorie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.spalone_kalorie)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.kategoria)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.kategoria.nazwa)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id_cwiczenia">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApplication/Views/Cwiczenie/Edit.cshtml
@model WebApplication.Models.Cwiczenie

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Cwiczenie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id_cwiczenia" />
            <div class="form-group">
                <label asp-for="nazwa" class="control-label"></label>
                <input asp-for="nazwa" class="form-control" />
                <span asp-validation-for="nazwa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="opis" class="control-label"></label>
                <input asp-for="opis" class="form-control" />
                <span asp-validation-for="opis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="spalone_kalorie" class="control-label"></label>
                <input asp-for="spalone_kalorie" class="form-control" />
                <span asp-validation-for="spalone_kalorie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="id_kategorii" class="control-label"></label>
                <select asp-for="id_kategorii" class="form-control" asp-items="ViewBag.id_kategorii"></select>
                <span asp-validation-for="id_kategorii" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication/Views/Cwiczenie/Index.cshtml
@model IEnumerable<WebApplication.Models.Cwiczenie>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
@using (Html.BeginForm("Index", "Cwiczenie", FormMethod.Get))
{
<fieldset>
    @Html.TextBox("searchString")

    @Html.DropDownList("category")

    <p>
        <input type="submit" value="Filtruj" />
    </p>

</fieldset>
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.nazwa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.opis)
            </th>
            <th>
                <a asp-action="Index" asp-route-sort="@ViewData["currentSort"]" asp-route-searchString="@ViewData["currentSearchString"]">
                    @Html.DisplayNameFor(model => model.spalone_kalorie)
                    @if ((int)ViewData["currentSort"] == 0)
                    {
                        <p>▲</p>
                    }
                    else if ((int)ViewData["currentSort"] == 2)
                    {
                        <p>▼</p>
                    }
                    
                </a>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.kategoria)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nazwa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.opis)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.spalone_kalorie)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.kategoria.nazwa)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.id_cwiczenia">Details</a> <br />

                @if (ViewBag.isTrainer)
                {
                    <a asp-action="Edit" asp-route-id="@item.id_cwiczenia">Edit</a> <br />
                    <a asp-action="Delete" asp-route-id="@item.id_cwiczenia">Delete</a> <br />
                }

            </td>
        </tr>
}
    </tbody>
</table>